### ISSUE TITLE
PdfConfig findExecutable does not find the installed wkhtmltopdf

### ISSUE THREAD

**Issue by gxof** [cloudify/sPDF#33]
Hello,

I use "yum install" and the package wkhtmltopdf is installed in /usr/local/bin.
A manual "which wkhtmltopdf" gives me `/usr/local/bin/wkhtmltopdf` where PdfConfig findExecutable seems (if I understand the code) to find nothing.
Consequently I cannot render/create pdf.
Do you have an idea about the problem and how I can solve it?

I don't know if the next information is relevant but I would like to add that the error states: 
`No wkhtmltopdf executable found at /sbin:/bin:/usr/sbin:/usr/bin` (only those 4)
where a `echo $PATH` gives
`/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin: ...`

Thanks

Gerald

**Comment by cloudify** [comment]
Hi Gerald,

do you get a `NoExecutableException`? If that's the case, try to manually specify the path to the `wkhtmltopdf` when you instantiate the `Pdf` object:

```
val pdf = Pdf("/usr/local/bin/wkhtmltopdf", PdfConfig.default)
```

**Comment by gxof** [comment]
Yes it is a this exception being thrown. Setting manually the path does work too, but I was looking for a solution where I don't hardcode the path.
I checked my bashrc, it seems fine but the my application shell is not saying anything but the 4 path that I mentioned.
:/
I think it is a usual matter for a linux pro, but I can't find a clean workaround. Do you have any other option except hardcoding?

Thanks 

Gerald

**Comment by cloudify** [comment]
Another option would be for lookup the location yourself with some Scala code before instantiating the `Pdf` class. If you find the `wkhtmltopdf` executable, you pass it to `Pdf`, if you don't, you throw an error.
